export const roomsData = [
  {
    roomType: "Standard Twin Room",
    beds: ["2 Twin Beds"],
    amenities: [
      { icon: "Home", label: "1 Room" },
      { icon: "Ruler", label: "269 feet²" },
      { icon: "Tree", label: "Inner courtyard view" },
      { icon: "Wind", label: "Air conditioning" },
      { icon: "Bath", label: "Attached bathroom" },
      { icon: "Tv", label: "Flat-screen TV" },
      { icon: "Coffee", label: "Coffee machine" },
    ],
    otherAmenities: [
      "Free Wifi",
      "Free toiletries",
      "Bathrobe",
      "Safe",
      "Toilet",
      "Bathtub or shower",
      "Towels",
      "Linens",
      "Socket near the bed",
      "Desk",
      "TV",
      "Slippers",
      "Refrigerator",
      "Telephone",
      "Ironing facilities",
      "Satellite channels",
      "Tea/Coffee maker",
      "Iron",
      "Heating",
      "Hairdryer",
      "Wake-up service/Alarm clock",
    ],
    options: [
      {
        guests: 2,
        price: 225,
        includes: "includes taxes and fees",
        choices: [
          { icon: "CupSoda", label: "Excellent breakfast for $21.20" },
          { icon: "Check", label: "Includes 20% off food/drink" },
          { icon: "FcCancel", label: "Non-refundable" },
        ],
        payment: "Pay the property before arrival",
      },
      {
        guests: 1,
        price: 250,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Coffee", label: "Gourmet breakfast included" },
          { icon: "Check", label: "Premium coffee and pastries included" },
          { icon: "FcCancel", label: "Fully refundable" },
        ],
        payment: "Free cancellation before arrival",
      },
      {
        guests: 2,
        price: 275,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Utensils", label: "Half-board meal plan for $40.00" },
          { icon: "Check", label: "Includes breakfast & dinner" },
          { icon: "FcCancel", label: "Cancellation fee applies" },
        ],
        payment: "Flexible payment options available",
      },
      {
        guests: 1,
        price: 300,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Wine", label: "All-inclusive package for $120.00" },
          { icon: "Check", label: "Free drinks & snacks included" },
          {
            icon: "FcCancel",
            label: "Refundable up to 24 hours before check-in",
          },
        ],
        payment: "Pay now or at check-in",
      },
    ],
  },
  {
    roomType: "Executive Suite",
    beds: ["1 King Bed", "1 Sofa Bed"],
    amenities: [
      { icon: "Home", label: "1 Suite" },
      { icon: "Ruler", label: "500 feet²" },
      { icon: "City", label: "Panoramic city view" },
      { icon: "Wind", label: "Central air conditioning" },
      { icon: "Bath", label: "Spa-style bathroom" },
      { icon: "Tv", label: "65-inch OLED TV" },
      { icon: "Coffee", label: "In-room barista coffee station" },
    ],
    otherAmenities: [
      "Free high-speed Wifi",
      "Private balcony",
      "Premium bath products",
      "Smart room controls",
      "Complimentary mini-bar",
      "Soundproof walls",
      "Heated floors",
      "Luxury bathrobes & slippers",
      "Personalized concierge service",
      "Satellite channels",
      "Tea/Coffee maker",
      "Iron",
      "Heating",
      "Hairdryer",
      "Wake-up service/Alarm clock",
    ],
    options: [
      {
        guests: 2,
        price: 450,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Wine", label: "Exclusive wine & cheese tasting" },
          { icon: "Check", label: "Priority check-in & late checkout" },
          {
            icon: "FcCancel",
            label: "Refundable up to 48 hours before check-in",
          },
        ],
        payment: "Pay now or at check-in",
      },
      {
        guests: 1,
        price: 500,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Utensils", label: "Half-board meal plan for $80.00" },
          { icon: "Check", label: "Dedicated personal assistant" },
          { icon: "FcCancel", label: "Fully refundable" },
        ],
        payment: "Free cancellation before arrival",
      },
      {
        guests: 2,
        price: 550,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Crown", label: "VIP spa access & massage" },
          { icon: "Check", label: "Luxury chauffeur service" },
          {
            icon: "FcCancel",
            label: "Refundable up to 24 hours before check-in",
          },
        ],
        payment: "Flexible payment options available",
      },
      {
        guests: 1,
        price: 600,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Plane", label: "Private airport transfer" },
          { icon: "Check", label: "Custom gourmet dining experience" },
          { icon: "FcCancel", label: "Fully refundable with no penalties" },
        ],
        payment: "Pay now or upon arrival",
      },
    ],
  },
  {
    roomType: "Deluxe King Room",
    beds: ["1 King Bed"],
    amenities: [
      { icon: "Home", label: "1 Room" },
      { icon: "Ruler", label: "350 feet²" },
      { icon: "Mountain", label: "Scenic view" },
      { icon: "Wind", label: "Air conditioning" },
      { icon: "Bath", label: "Attached luxury bathroom" },
      { icon: "Tv", label: "Smart TV with streaming" },
      { icon: "Coffee", label: "Espresso machine" },
    ],
    otherAmenities: [
      "Free Wifi",
      "Jacuzzi",
      "Premium bathrobe",
      "In-room safe",
      "Luxury toiletries",
      "Rainfall shower",
      "Heated floors",
      "Mini-bar",
      "Nespresso machine",
      "Exclusive concierge service",
      "Satellite channels",
      "Tea/Coffee maker",
      "Iron",
      "Heating",
      "Hairdryer",
      "Wake-up service/Alarm clock",
    ],
    options: [
      {
        guests: 2,
        price: 350,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Wine", label: "All-inclusive package for $150.00" },
          { icon: "Check", label: "VIP lounge access" },
          {
            icon: "FcCancel",
            label: "Refundable up to 48 hours before check-in",
          },
        ],
        payment: "Pay now or at check-in",
      },
      {
        guests: 1,
        price: 400,
        includes: "includes taxes and fees",
        choices: [
          { icon: "Utensils", label: "Half-board meal plan for $60.00" },
          { icon: "Check", label: "Personalized butler service" },
          { icon: "FcCancel", label: "Fully refundable" },
        ],
        payment: "Free cancellation before arrival",
      },
    ],
  },
];
