export const products = [
  {
    name: "Sony PlayStation 5 Digital Edition",
    category: "Gaming",
    price: 499.99,
    datePublished: "2023",
    tags: ["White", "12+", "Free Shipping"],
    manufacturer: "Sony",
    image: "/Ps5.png",
  },
  {
    name: "Apple MacBook Pro M3 - 16-inch",
    category: "Electronics",
    price: 2499.99,
    datePublished: "2024",
    tags: ["Black", "18+", "Next Day Delivery"],
    manufacturer: "Apple",
    image: "/Macm3.png",
  },
  {
    name: "Samsung Galaxy S24 Ultra - 512GB",
    category: "Electronics",
    price: 1299.99,
    datePublished: "2022",
    tags: ["Black", "16+", "Cash on Delivery"],
    manufacturer: "Samsung",
    image: "/S24.png",
  },
  {
    name: "LG OLED evo G3 65” 4K Smart TV",
    category: "Home Appliances",
    price: 2299.99,
    datePublished: "2025",
    tags: ["White", "12+", "Free Shipping"],
    manufacturer: "LG",
    image: "/LGOLED.png",
  },
  {
    name: "Sony WH-1000XM5 Noise Cancelling Headphones",
    category: "Electronics",
    price: 399.99,
    datePublished: "2021",
    tags: ["Black", "18+", "Next Day Delivery"],
    manufacturer: "Sony",
    image: "/SonyWH-1000XM5.png",
  },
  {
    name: "Sony Xperia 5 V 5G Smartphone",
    category: "Electronics",
    price: 899,
    datePublished: "2024",
    tags: ["Black", "16+", "Next Day Delivery"],
    manufacturer: "Sony",
    image: "/SonyXperia.png",
  },
  {
    name: "Apple MacBook Pro 14-inch M3",
    category: "Electronics",
    price: 1999,
    datePublished: "2023",
    tags: ["White", "18+", "Cash on Delivery"],
    manufacturer: "Apple",
    image: "/Mac14m3.png",
  },
  {
    name: "Samsung QN90C Neo QLED 65-inch Smart TV",
    category: "Home Appliances",
    price: 1499,
    datePublished: "2025",
    tags: ["Black", "12+", "Free Shipping"],
    manufacturer: "Samsung",
    image: "/Qn90c.png",
  },
  {
    name: "LG UltraGear 27GN950-B 4K Gaming Monitor",
    category: "Gaming",
    price: 799,
    datePublished: "2022",
    tags: ["Black", "16+", "Next Day Delivery"],
    manufacturer: "LG",
    image: "/27gn950-b.png",
  },
  {
    name: "Sony WH-1000XM5 Noise-Canceling Headphones",
    category: "Electronics",
    price: 349,
    datePublished: "2023",
    tags: ["White", "18+", "Cash on Delivery"],
    manufacturer: "Sony",
    image: "/Wh-1000xm5.png",
  },
];
