export const customers = [
  {
    customer: "Alice Johnson",
    email: "alice.johnson@example.com",
    orders: 15,
    totalSpent: 2345.5,
    city: "New York",
    dateJoined: "2021-03-15",
  },
  {
    customer: "Bob Smith",
    email: "bob.smith@example.com",
    orders: 8,
    totalSpent: 987.99,
    city: "Los Angeles",
    dateJoined: "2022-06-22",
  },
  {
    customer: "Charlie Davis",
    email: "charlie.davis@example.com",
    orders: 22,
    totalSpent: 3476.25,
    city: "Chicago",
    dateJoined: "2020-11-05",
  },
  {
    customer: "Diana Lopez",
    email: "diana.lopez@example.com",
    orders: 5,
    totalSpent: 524.0,
    city: "Houston",
    dateJoined: "2023-01-10",
  },
  {
    customer: "Ethan Williams",
    email: "ethan.williams@example.com",
    orders: 12,
    totalSpent: 1840.75,
    city: "San Francisco",
    dateJoined: "2021-07-19",
  },
  {
    customer: "Fiona Brown",
    email: "fiona.brown@example.com",
    orders: 19,
    totalSpent: 2785.99,
    city: "Seattle",
    dateJoined: "2020-09-28",
  },
  {
    customer: "George Miller",
    email: "george.miller@example.com",
    orders: 3,
    totalSpent: 300.0,
    city: "Miami",
    dateJoined: "2024-02-01",
  },
  {
    customer: "Hannah Wilson",
    email: "hannah.wilson@example.com",
    orders: 11,
    totalSpent: 1675.3,
    city: "Austin",
    dateJoined: "2022-04-13",
  },
  {
    customer: "Ian Clark",
    email: "ian.clark@example.com",
    orders: 6,
    totalSpent: 689.5,
    city: "Boston",
    dateJoined: "2023-05-27",
  },
  {
    customer: "Jessica Martinez",
    email: "jessica.martinez@example.com",
    orders: 20,
    totalSpent: 3150.8,
    city: "Denver",
    dateJoined: "2019-12-09",
  },
];
