export const filters = [
  {
    name: "Price Per Night (£)",
    tag: "pricePerNight",
    type: "range",
    items: ["Min", "Max"],
  },
  {
    name: "Property Type",
    tag: "propertyType",
    type: "array",
    items: [
      { label: "hotel", checked: false },
      { label: "apartment", checked: false },
      { label: "penthouse", checked: false },
      { label: "hostel", checked: false },
      { label: "guesthouse", checked: false },
      { label: "townhouse", checked: false },
      { label: "studio", checked: false },
      { label: "loft", checked: false },
    ],
  },
  {
    name: "Borough/Area",
    tag: "borough",
    type: "array",
    items: [
      { label: "Westminster", checked: false },
      { label: "Camden", checked: false },
      { label: "Kensington", checked: false },
      { label: "Chelsea", checked: false },
      { label: "Soho", checked: false },
      { label: "Shoreditch", checked: false },
      { label: "Canary Wharf", checked: false },
      { label: "Greenwich", checked: false },
    ],
  },

  {
    name: "Guest Capacity",
    tag: "guestCapacity",
    type: "number",
    items: [1, 2, 3, 4, 5],
  },
  {
    name: "Bedrooms",
    tag: "bedrooms",
    type: "number",
    items: [1, 2, 3, 4, 5],
  },
  {
    name: "Bathrooms",
    tag: "bathrooms",
    type: "number",
    items: [1, 2, 3, 4, 5],
  },
  {
    name: "Amenities",
    tag: "amenities",
    type: "array",
    items: [
      { label: "WiFi", checked: false },
      { label: "Gym", checked: false },
      { label: "Concierge", checked: false },
      { label: "Kitchen", checked: false },
      { label: "Pet-friendly", checked: false },
      { label: "Rooftop Terrace", checked: false },
      { label: "24/7 Security", checked: false },
      { label: "Business Lounge", checked: false },
    ],
  },
  {
    name: "Rating",
    tag: "rating",
    type: "number",
    items: [1, 2, 3, 4, 5],
  },
  {
    name: "Booking Flexibility",
    tag: "bookingFlexibility",
    type: "array",
    items: [
      { label: "Free cancellation", checked: false },
      { label: "Non-refundable", checked: false },
      { label: "Pay later", checked: false },
    ],
  },
  {
    name: "Nearby Transport",
    tag: "nearbyTransport",
    type: "array",
    items: [
      { label: "London Underground", checked: false },
      { label: "Overground", checked: false },
      { label: "National Rail", checked: false },
      { label: "Bus access", checked: false },
    ],
  },
  {
    name: "View Type",
    tag: "viewType",
    type: "array",
    items: [
      { label: "River Thames", checked: false },
      { label: "Skyline", checked: false },
      { label: "Garden View", checked: false },
      { label: "City View", checked: false },
    ],
  },
  {
    name: "Property Rules",
    tag: "propertyRules",
    type: "array",
    items: [
      { label: "No smoking", checked: false },
      { label: "No parties", checked: false },
      { label: "Quiet hours", checked: false },
      { label: "Check-in: 3 PM, Check-out: 11 AM", checked: false },
    ],
  },
  {
    name: "Nearby Attractions",
    tag: "nearbyAttractions",
    type: "array",
    items: [
      { label: "Tower Bridge", checked: false },
      { label: "Buckingham Palace", checked: false },
      { label: "The Shard", checked: false },
      { label: "Big Ben", checked: false },
      { label: "Hyde Park", checked: false },
      { label: "West End", checked: false },
    ],
  },
];

export interface Property {
  id: string;
  name: string;
  image: string;
  pricePerNight: number;
  propertyType: string[];
  borough: string[];
  guestCapacity: number;
  bedrooms: number;
  bathrooms: number;
  amenities: string[];
  rating: number;
  bookingFlexibility: string[];
  nearbyTransport: string[];
  viewType: string[];
  propertyRules: string[];
  nearbyAttractions: string[];
  location: {
    latitude: number;
    longitude: number;
  };
}

export const properties: Property[] = [
  {
    id: "1",
    name: "Luxury Apartment in Camden",
    pricePerNight: 250,
    propertyType: ["apartment"],
    borough: ["Camden"],
    guestCapacity: 3,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Concierge"],
    rating: 4,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Skyline"],
    propertyRules: ["No smoking", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["Hyde Park", "The Shard"],
    location: { latitude: 51.5413, longitude: -0.1467 },
    image: "https://source.unsplash.com/400x300/?apartment",
  },

  {
    id: "2",
    name: "Riverside Penthouse in Westminster",
    pricePerNight: 400,
    propertyType: ["penthouse"],
    borough: ["Westminster"],
    guestCapacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Rooftop Terrace", "24/7 Security"],
    rating: 5,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "National Rail"],
    viewType: ["River Thames"],
    propertyRules: ["No parties", "Quiet hours"],
    nearbyAttractions: ["Big Ben", "Buckingham Palace"],
    location: { latitude: 51.4995, longitude: -0.1333 },
    image: "https://source.unsplash.com/400x300/?penthouse",
  },
  {
    id: "3",
    name: "Cozy Loft in Shoreditch",
    pricePerNight: 180,
    propertyType: ["loft"],
    borough: ["Shoreditch"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Business Lounge"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["Overground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "Quiet hours"],
    nearbyAttractions: ["Tower Bridge", "The Shard"],
    location: { latitude: 51.5245, longitude: -0.0788 },
    image: "https://source.unsplash.com/400x300/?loft",
  },
  {
    id: "4",
    name: "Modern Studio in Canary Wharf",
    pricePerNight: 220,
    propertyType: ["studio"],
    borough: ["Canary Wharf"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Gym", "Concierge"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Overground"],
    viewType: ["River Thames", "Skyline"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["West End", "The Shard"],
    location: { latitude: 51.5054, longitude: -0.0235 },
    image: "https://source.unsplash.com/400x300/?studio",
  },
  {
    id: "5",
    name: "Townhouse in Kensington",
    pricePerNight: 350,
    propertyType: ["townhouse"],
    borough: ["Kensington"],
    guestCapacity: 6,
    bedrooms: 4,
    bathrooms: 3,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 5,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground"],
    viewType: ["Garden View"],
    propertyRules: ["Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["Hyde Park", "Buckingham Palace"],
    location: { latitude: 51.501, longitude: -0.1932 },
    image: "https://source.unsplash.com/400x300/?townhouse",
  },
  {
    id: "6",
    name: "Luxury Penthouse in Canary Wharf",
    pricePerNight: 500,
    propertyType: ["penthouse"],
    borough: ["Canary Wharf"],
    guestCapacity: 4,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Gym", "Concierge", "Rooftop Terrace"],
    rating: 5,
    bookingFlexibility: ["Free cancellation", "Pay later"],
    nearbyTransport: ["London Underground", "Overground"],
    viewType: ["Skyline", "River Thames"],
    propertyRules: ["No parties", "No smoking"],
    nearbyAttractions: ["Tower Bridge", "The Shard"],
    location: { latitude: 51.5055, longitude: -0.0209 },
    image: "https://source.unsplash.com/400x300/?penthouse",
  },
  {
    id: "7",
    name: "Cozy Loft in Shoreditch",
    pricePerNight: 180,
    propertyType: ["loft"],
    borough: ["Shoreditch"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "Quiet hours"],
    nearbyAttractions: ["West End", "The Shard"],
    location: { latitude: 51.524, longitude: -0.0782 },
    image: "https://source.unsplash.com/400x300/?loft",
  },
  {
    id: "8",
    name: "Modern Apartment in Soho",
    pricePerNight: 250,
    propertyType: ["apartment"],
    borough: ["Soho"],
    guestCapacity: 3,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "24/7 Security"],
    rating: 5,
    bookingFlexibility: ["Pay later", "Free cancellation"],
    nearbyTransport: ["London Underground", "National Rail"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["West End", "Buckingham Palace"],
    location: { latitude: 51.5136, longitude: -0.1365 },
    image: "https://source.unsplash.com/400x300/?apartment",
  },
  {
    id: "9",
    name: "Budget Hostel in Camden",
    pricePerNight: 75,
    propertyType: ["hostel"],
    borough: ["Camden"],
    guestCapacity: 1,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Concierge"],
    rating: 3,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Garden View"],
    propertyRules: ["Quiet hours", "No parties"],
    nearbyAttractions: ["Hyde Park", "Big Ben"],
    location: { latitude: 51.5406, longitude: -0.1434 },
    image: "https://source.unsplash.com/400x300/?hostel",
  },
  {
    id: "10",
    name: "Riverside Studio in Greenwich",
    pricePerNight: 220,
    propertyType: ["studio"],
    borough: ["Greenwich"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["National Rail", "Bus access"],
    viewType: ["River Thames"],
    propertyRules: ["No smoking", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["Tower Bridge", "The Shard"],
    location: { latitude: 51.4826, longitude: -0.0077 },
    image: "https://source.unsplash.com/400x300/?studio",
  },
  {
    id: "11",
    name: "Elegant Guesthouse in Westminster",
    pricePerNight: 280,
    propertyType: ["guesthouse"],
    borough: ["Westminster"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "24/7 Security", "Concierge"],
    rating: 5,
    bookingFlexibility: ["Pay later", "Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "Quiet hours"],
    nearbyAttractions: ["Big Ben", "Buckingham Palace"],
    location: { latitude: 51.4995, longitude: -0.1357 },
    image: "https://source.unsplash.com/400x300/?guesthouse",
  },
  {
    id: "12",
    name: "Spacious Apartment in Chelsea",
    pricePerNight: 400,
    propertyType: ["apartment"],
    borough: ["Chelsea"],
    guestCapacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Gym", "Kitchen", "Concierge"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground"],
    viewType: ["Skyline"],
    propertyRules: ["No parties", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["The Shard", "Hyde Park"],
    location: { latitude: 51.4875, longitude: -0.168 },
    image: "https://source.unsplash.com/400x300/?apartment",
  },
  {
    id: "13",
    name: "Budget Hotel in Canary Wharf",
    pricePerNight: 120,
    propertyType: ["hotel"],
    borough: ["Canary Wharf"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "24/7 Security"],
    rating: 3,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["London Underground", "Overground"],
    viewType: ["River Thames"],
    propertyRules: ["No smoking", "Quiet hours"],
    nearbyAttractions: ["Tower Bridge", "The Shard"],
    location: { latitude: 51.5052, longitude: -0.0235 },
    image: "https://source.unsplash.com/400x300/?hotel",
  },
  {
    id: "14",
    name: "Stylish Studio in Camden",
    pricePerNight: 200,
    propertyType: ["studio"],
    borough: ["Camden"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["Hyde Park", "West End"],
    location: { latitude: 51.5406, longitude: -0.1434 },
    image: "https://source.unsplash.com/400x300/?studio",
  },
  {
    id: "15",
    name: "Penthouse with River View in Greenwich",
    pricePerNight: 450,
    propertyType: ["penthouse"],
    borough: ["Greenwich"],
    guestCapacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["WiFi", "Gym", "Concierge", "Rooftop Terrace"],
    rating: 5,
    bookingFlexibility: ["Free cancellation", "Pay later"],
    nearbyTransport: ["National Rail", "Bus access"],
    viewType: ["River Thames", "Skyline"],
    propertyRules: ["No smoking", "No parties"],
    nearbyAttractions: ["Tower Bridge", "The Shard"],
    location: { latitude: 51.4826, longitude: -0.0077 },
    image: "https://source.unsplash.com/400x300/?penthouse",
  },
  {
    id: "16",
    name: "Luxury Loft in Shoreditch",
    pricePerNight: 380,
    propertyType: ["loft"],
    borough: ["Shoreditch"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Gym", "Concierge", "Rooftop Terrace"],
    rating: 5,
    bookingFlexibility: ["Pay later", "Free cancellation"],
    nearbyTransport: ["London Underground", "Overground"],
    viewType: ["Skyline", "City View"],
    propertyRules: ["No parties", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["West End", "Big Ben"],
    location: { latitude: 51.526, longitude: -0.078 },
    image: "https://source.unsplash.com/400x300/?loft",
  },
  {
    id: "17",
    name: "Modern Townhouse in Soho",
    pricePerNight: 420,
    propertyType: ["townhouse"],
    borough: ["Soho"],
    guestCapacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["WiFi", "Kitchen", "Concierge", "24/7 Security"],
    rating: 5,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "No parties"],
    nearbyAttractions: ["West End", "Buckingham Palace"],
    location: { latitude: 51.5136, longitude: -0.1365 },
    image: "https://source.unsplash.com/400x300/?townhouse",
  },
  {
    id: "18",
    name: "Chic Studio in Westminster",
    pricePerNight: 190,
    propertyType: ["studio"],
    borough: ["Westminster"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking", "Quiet hours"],
    nearbyAttractions: ["Big Ben", "Tower Bridge"],
    location: { latitude: 51.4975, longitude: -0.1357 },
    image: "https://source.unsplash.com/400x300/?studio",
  },
  {
    id: "19",
    name: "Boutique Hotel in Camden",
    pricePerNight: 250,
    propertyType: ["hotel"],
    borough: ["Camden"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "24/7 Security", "Concierge"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["London Underground"],
    viewType: ["Garden View"],
    propertyRules: ["No smoking", "Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["Hyde Park", "West End"],
    location: { latitude: 51.529, longitude: -0.1257 },
    image: "https://source.unsplash.com/400x300/?hotel",
  },
  {
    id: "20",
    name: "Scenic Penthouse in Canary Wharf",
    pricePerNight: 500,
    propertyType: ["penthouse"],
    borough: ["Canary Wharf"],
    guestCapacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["WiFi", "Gym", "Rooftop Terrace", "Concierge"],
    rating: 5,
    bookingFlexibility: ["Free cancellation", "Pay later"],
    nearbyTransport: ["London Underground", "National Rail"],
    viewType: ["River Thames", "Skyline"],
    propertyRules: ["No parties", "No smoking"],
    nearbyAttractions: ["The Shard", "Tower Bridge"],
    location: { latitude: 51.5033, longitude: -0.0183 },
    image: "https://source.unsplash.com/400x300/?penthouse",
  },
  {
    id: "21",
    name: "Elegant Penthouse in Mayfair",
    pricePerNight: 850,
    propertyType: ["penthouse"],
    borough: ["Mayfair"],
    guestCapacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["WiFi", "Concierge", "Rooftop Terrace", "24/7 Security"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Skyline"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["Buckingham Palace", "West End"],
    location: { latitude: 51.5107, longitude: -0.15 },
    image: "https://source.unsplash.com/400x300/?penthouse",
  },
  {
    id: "22",
    name: "Modern Apartment in Canary Wharf",
    pricePerNight: 300,
    propertyType: ["apartment"],
    borough: ["Canary Wharf"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Gym", "Kitchen"],
    rating: 4,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["National Rail", "Bus access"],
    viewType: ["River Thames"],
    propertyRules: ["Quiet hours"],
    nearbyAttractions: ["The Shard", "Tower Bridge"],
    location: { latitude: 51.5053, longitude: -0.02 },
    image: "https://source.unsplash.com/400x300/?apartment",
  },
  {
    id: "23",
    name: "Cozy Townhouse in Greenwich",
    pricePerNight: 275,
    propertyType: ["townhouse"],
    borough: ["Greenwich"],
    guestCapacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["Overground", "Bus access"],
    viewType: ["Garden View"],
    propertyRules: ["No parties"],
    nearbyAttractions: ["Cutty Sark", "Greenwich Park"],
    location: { latitude: 51.4811, longitude: -0.0048 },
    image: "https://source.unsplash.com/400x300/?townhouse",
  },
  {
    id: "24",
    name: "Boutique Hotel in Chelsea",
    pricePerNight: 400,
    propertyType: ["hotel"],
    borough: ["Chelsea"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Concierge", "Business Lounge"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["Sloane Square", "Saatchi Gallery"],
    location: { latitude: 51.4875, longitude: -0.1684 },
    image: "https://source.unsplash.com/400x300/?hotel",
  },
  {
    id: "25",
    name: "Riverside Loft in Battersea",
    pricePerNight: 250,
    propertyType: ["loft"],
    borough: ["Battersea"],
    guestCapacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen"],
    rating: 4,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["River Thames"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["Battersea Park", "Battersea Power Station"],
    location: { latitude: 51.4817, longitude: -0.1458 },
    image: "https://source.unsplash.com/400x300/?loft",
  },
  {
    id: "26",
    name: "Luxury Studio in Soho",
    pricePerNight: 320,
    propertyType: ["studio"],
    borough: ["Soho"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Gym", "Concierge"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No parties"],
    nearbyAttractions: ["West End", "Piccadilly Circus"],
    location: { latitude: 51.5138, longitude: -0.1365 },
    image: "https://source.unsplash.com/400x300/?studio",
  },
  {
    id: "27",
    name: "Classic Hotel in Westminster",
    pricePerNight: 450,
    propertyType: ["hotel"],
    borough: ["Westminster"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Concierge", "24/7 Security"],
    rating: 5,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "National Rail"],
    viewType: ["City View"],
    propertyRules: ["Check-in: 3 PM, Check-out: 11 AM"],
    nearbyAttractions: ["Big Ben", "Buckingham Palace"],
    location: { latitude: 51.5014, longitude: -0.1256 },
    image: "https://source.unsplash.com/400x300/?hotel",
  },
  {
    id: "28",
    name: "Rooftop Loft in Shoreditch",
    pricePerNight: 290,
    propertyType: ["loft"],
    borough: ["Shoreditch"],
    guestCapacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Rooftop Terrace"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["Overground", "Bus access"],
    viewType: ["Skyline"],
    propertyRules: ["Quiet hours"],
    nearbyAttractions: ["Brick Lane", "Spitalfields Market"],
    location: { latitude: 51.5238, longitude: -0.078 },
    image: "https://source.unsplash.com/400x300/?loft",
  },
  {
    id: "29",
    name: "Penthouse in Kensington",
    pricePerNight: 750,
    propertyType: ["penthouse"],
    borough: ["Kensington"],
    guestCapacity: 5,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["WiFi", "Gym", "Concierge", "Rooftop Terrace"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Skyline"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["Hyde Park", "Kensington Palace"],
    location: { latitude: 51.5015, longitude: -0.1905 },
    image: "https://source.unsplash.com/400x300/?penthouse",
  },
  {
    id: "30",
    name: "Modern Apartment in Camden",
    pricePerNight: 280,
    propertyType: ["apartment"],
    borough: ["Camden"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["Overground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No parties"],
    nearbyAttractions: ["Camden Market", "Regent's Park"],
    location: { latitude: 51.5406, longitude: -0.1433 },
    image: "https://source.unsplash.com/400x300/?apartment",
  },
  {
    id: "31",
    name: "Guesthouse in Greenwich",
    pricePerNight: 200,
    propertyType: ["guesthouse"],
    borough: ["Greenwich"],
    guestCapacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen"],
    rating: 3,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["National Rail", "Bus access"],
    viewType: ["Garden View"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["Royal Observatory", "Cutty Sark"],
    location: { latitude: 51.4825, longitude: -0.0074 },
    image: "https://source.unsplash.com/400x300/?guesthouse",
  },
  {
    id: "32",
    name: "Townhouse in Chelsea",
    pricePerNight: 370,
    propertyType: ["townhouse"],
    borough: ["Chelsea"],
    guestCapacity: 5,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No parties"],
    nearbyAttractions: ["Saatchi Gallery", "King's Road"],
    location: { latitude: 51.4861, longitude: -0.1693 },
    image: "https://source.unsplash.com/400x300/?townhouse",
  },
  {
    id: "33",
    name: "Minimalist Loft in Canary Wharf",
    pricePerNight: 280,
    propertyType: ["loft"],
    borough: ["Canary Wharf"],
    guestCapacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Gym", "Kitchen"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["River Thames"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["The Shard", "Tower Bridge"],
    location: { latitude: 51.5065, longitude: -0.0196 },
    image: "https://source.unsplash.com/400x300/?loft",
  },
  {
    id: "34",
    name: "Luxury Hotel in Mayfair",
    pricePerNight: 900,
    propertyType: ["hotel"],
    borough: ["Mayfair"],
    guestCapacity: 6,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["WiFi", "Concierge", "Business Lounge", "24/7 Security"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Skyline"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["Buckingham Palace", "West End"],
    location: { latitude: 51.512, longitude: -0.147 },
    image: "https://source.unsplash.com/400x300/?hotel",
  },
  {
    id: "35",
    name: "Scenic Riverside Apartment",
    pricePerNight: 310,
    propertyType: ["apartment"],
    borough: ["Battersea"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Kitchen", "Balcony"],
    rating: 4,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["River Thames"],
    propertyRules: ["No parties"],
    nearbyAttractions: ["Battersea Park", "Chelsea Bridge"],
    location: { latitude: 51.4781, longitude: -0.148 },
    image: "https://source.unsplash.com/400x300/?apartment",
  },
  {
    id: "36",
    name: "Elegant Suite in Knightsbridge",
    pricePerNight: 620,
    propertyType: ["suite"],
    borough: ["Knightsbridge"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Concierge", "Room Service"],
    rating: 5,
    bookingFlexibility: ["Free cancellation"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["Check-in: 3 PM, Check-out: 12 PM"],
    nearbyAttractions: ["Harrods", "Hyde Park"],
    location: { latitude: 51.5013, longitude: -0.1604 },
    image: "https://source.unsplash.com/400x300/?suite",
  },
  {
    id: "37",
    name: "Quaint Cottage in Richmond",
    pricePerNight: 250,
    propertyType: ["cottage"],
    borough: ["Richmond"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["WiFi", "Garden", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["National Rail", "Bus access"],
    viewType: ["Garden View"],
    propertyRules: ["No loud music"],
    nearbyAttractions: ["Richmond Park", "Kew Gardens"],
    location: { latitude: 51.4613, longitude: -0.303 },
    image: "https://source.unsplash.com/400x300/?cottage",
  },
  {
    id: "38",
    name: "Skyline View Apartment in Canary Wharf",
    pricePerNight: 450,
    propertyType: ["apartment"],
    borough: ["Canary Wharf"],
    guestCapacity: 4,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["WiFi", "Gym", "Balcony"],
    rating: 5,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Skyline"],
    propertyRules: ["No smoking"],
    nearbyAttractions: ["The O2", "Greenwich Park"],
    location: { latitude: 51.5054, longitude: -0.0221 },
    image: "https://source.unsplash.com/400x300/?skyline",
  },
  {
    id: "39",
    name: "Cozy Studio in Notting Hill",
    pricePerNight: 275,
    propertyType: ["studio"],
    borough: ["Notting Hill"],
    guestCapacity: 2,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Kitchen", "Pet-friendly"],
    rating: 4,
    bookingFlexibility: ["Non-refundable"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["City View"],
    propertyRules: ["No parties"],
    nearbyAttractions: ["Portobello Road Market", "Holland Park"],
    location: { latitude: 51.511, longitude: -0.2054 },
    image: "https://source.unsplash.com/400x300/?studio",
  },
  {
    id: "40",
    name: "Charming Bed & Breakfast in Hampstead",
    pricePerNight: 190,
    propertyType: ["bed & breakfast"],
    borough: ["Hampstead"],
    guestCapacity: 3,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["WiFi", "Breakfast included", "Garden"],
    rating: 3,
    bookingFlexibility: ["Pay later"],
    nearbyTransport: ["London Underground", "Bus access"],
    viewType: ["Park View"],
    propertyRules: ["No pets"],
    nearbyAttractions: ["Hampstead Heath", "Kenwood House"],
    location: { latitude: 51.5567, longitude: -0.1784 },
    image: "https://source.unsplash.com/400x300/?bedandbreakfast",
  },
];
